// Code generated by mockery v2.20.0. DO NOT EDIT.

/*
# Module: agent/consul/rate/mock_RequestLimitsHandler.go
Mock Requestlimitshandler module for agent layer

## Tags
agent

## Exports
MockRequestLimitsHandler, NewMockRequestLimitsHandler

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<agent/consul/rate/mock_RequestLimitsHandler.go> a code:Module ;
    code:name "agent/consul/rate/mock_RequestLimitsHandler.go" ;
    code:description "Mock Requestlimitshandler module for agent layer" ;
    code:language "go" ;
    code:layer "agent" ;
    code:exports :MockRequestLimitsHandler, :NewMockRequestLimitsHandler ;
    code:tags "agent" .
<!-- End LinkedDoc RDF -->
*/
package rate

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRequestLimitsHandler is an autogenerated mock type for the RequestLimitsHandler type
type MockRequestLimitsHandler struct {
	mock.Mock
}

// Allow provides a mock function with given fields: op
func (_m *MockRequestLimitsHandler) Allow(op Operation) error {
	ret := _m.Called(op)

	var r0 error
	if rf, ok := ret.Get(0).(func(Operation) error); ok {
		r0 = rf(op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: serversStatusProvider
func (_m *MockRequestLimitsHandler) Register(serversStatusProvider ServersStatusProvider) {
	_m.Called(serversStatusProvider)
}

// Run provides a mock function with given fields: ctx
func (_m *MockRequestLimitsHandler) Run(ctx context.Context) {
	_m.Called(ctx)
}

// UpdateConfig provides a mock function with given fields: cfg
func (_m *MockRequestLimitsHandler) UpdateConfig(cfg HandlerConfig) {
	_m.Called(cfg)
}

// UpdateIPConfig provides a mock function with given fields: cfg
func (_m *MockRequestLimitsHandler) UpdateIPConfig(cfg IPLimitConfig) {
	_m.Called(cfg)
}

type mockConstructorTestingTNewMockRequestLimitsHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRequestLimitsHandler creates a new instance of MockRequestLimitsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRequestLimitsHandler(t mockConstructorTestingTNewMockRequestLimitsHandler) *MockRequestLimitsHandler {
	mock := &MockRequestLimitsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
