// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: private/pbstatus/status.proto

/*
# Module: proto/private/pbstatus/status.pb.binary.go
Status.Pb.Binary module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto/private/pbstatus/status.pb.binary.go> a code:Module ;
    code:name "proto/private/pbstatus/status.pb.binary.go" ;
    code:description "Status.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package pbstatus

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *Status) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *Status) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
