// Code generated by deep-copy -pointer-receiver -o ./catalog_schema.deepcopy.go -type upstreamDownstream ./; DO NOT EDIT.

/*
# Module: agent/consul/state/catalog_schema.deepcopy.go
Catalog Schema.Deepcopy module for agent layer

## Tags
agent, discovery, persistence, registry, storage

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<agent/consul/state/catalog_schema.deepcopy.go> a code:Module ;
    code:name "agent/consul/state/catalog_schema.deepcopy.go" ;
    code:description "Catalog Schema.Deepcopy module for agent layer" ;
    code:language "go" ;
    code:layer "agent" ;
    code:tags "agent", "discovery", "persistence", "registry", "storage" .
<!-- End LinkedDoc RDF -->
*/
package state

// DeepCopy generates a deep copy of *upstreamDownstream
func (o *upstreamDownstream) DeepCopy() *upstreamDownstream {
	var cp upstreamDownstream = *o
	if o.Refs != nil {
		cp.Refs = make(map[string]struct{}, len(o.Refs))
		for k2, v2 := range o.Refs {
			cp.Refs[k2] = v2
		}
	}
	return &cp
}
