// Code generated by protoc-json-shim. DO NOT EDIT.

/*
# Module: proto-public/pbconnectca/ca_json.gen.go
Ca Json.Gen module for internal layer

## Tags
internal, mtls, service-mesh

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbconnectca/ca_json.gen.go> a code:Module ;
    code:name "proto-public/pbconnectca/ca_json.gen.go" ;
    code:description "Ca Json.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal", "mtls", "service-mesh" .
<!-- End LinkedDoc RDF -->
*/
package pbconnectca

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for WatchRootsRequest
func (this *WatchRootsRequest) MarshalJSON() ([]byte, error) {
	str, err := CaMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for WatchRootsRequest
func (this *WatchRootsRequest) UnmarshalJSON(b []byte) error {
	return CaUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for WatchRootsResponse
func (this *WatchRootsResponse) MarshalJSON() ([]byte, error) {
	str, err := CaMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for WatchRootsResponse
func (this *WatchRootsResponse) UnmarshalJSON(b []byte) error {
	return CaUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for CARoot
func (this *CARoot) MarshalJSON() ([]byte, error) {
	str, err := CaMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CARoot
func (this *CARoot) UnmarshalJSON(b []byte) error {
	return CaUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for SignRequest
func (this *SignRequest) MarshalJSON() ([]byte, error) {
	str, err := CaMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SignRequest
func (this *SignRequest) UnmarshalJSON(b []byte) error {
	return CaUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for SignResponse
func (this *SignResponse) MarshalJSON() ([]byte, error) {
	str, err := CaMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SignResponse
func (this *SignResponse) UnmarshalJSON(b []byte) error {
	return CaUnmarshaler.Unmarshal(b, this)
}

var (
	CaMarshaler   = &protojson.MarshalOptions{}
	CaUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
