flowchart LR
    acl_acl_ce_go["acl/acl_ce.go"
    acl_policy_authorizer_ce_go["acl/policy_authorizer_ce.go"
    acl_policy_ce_go["acl/policy_ce.go"
    acl_enterprisemeta_ce_go["acl/enterprisemeta_ce.go"
    acl_validation_go["acl/validation.go"
    acl_resolver_result_go["acl/resolver/result.go"
    acl_policy_go["acl/policy.go"
    acl_policy_merger_ce_go["acl/policy_merger_ce.go"
    acl_static_authorizer_go["acl/static_authorizer.go"
    acl_acl_go["acl/acl.go"
    acl_authorizer_ce_go["acl/authorizer_ce.go"
    acl_errors_go["acl/errors.go"
    acl_errors_ce_go["acl/errors_ce.go"
    acl_MockAuthorizer_go["acl/MockAuthorizer.go"
    acl_chained_authorizer_go["acl/chained_authorizer.go"
    acl_testing_go["acl/testing.go"
    acl_authorizer_go["acl/authorizer.go"
    acl_policy_authorizer_go["acl/policy_authorizer.go"
    acl_policy_merger_go["acl/policy_merger.go"
    acl_resolver_danger_go["acl/resolver/danger.go"


