flowchart LR
    connect_service_go["connect/service.go"
    connect_resolver_go["connect/resolver.go"
    agent_xds_server_go["agent/xds/server.go"
    connect_proxy_listener_go["connect/proxy/listener.go"
    connect_certgen_certgen_go["connect/certgen/certgen.go"
    test_integration_connect_envoy_test_sds_server_sds_go["test/integration/connect/envoy/test-sds-server/sds.go"
    connect_proxy_config_go["connect/proxy/config.go"
    connect_testing_go["connect/testing.go"
    connect_proxy_conn_go["connect/proxy/conn.go"
    connect_proxy_proxy_go["connect/proxy/proxy.go"
    connect_proxy_testing_go["connect/proxy/testing.go"
    agent_proxycfg_manager_go["agent/proxycfg/manager.go"
    connect_tls_go["connect/tls.go"


