// Code generated by mockery v2.12.2. DO NOT EDIT.

/*
# Module: agent/log-drop/mock_Logger.go
Mock Logger module for agent layer

## Tags
agent

## Exports
MockLogger, NewMockLogger

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<agent/log-drop/mock_Logger.go> a code:Module ;
    code:name "agent/log-drop/mock_Logger.go" ;
    code:description "Mock Logger module for agent layer" ;
    code:language "go" ;
    code:layer "agent" ;
    code:exports :MockLogger, :NewMockLogger ;
    code:tags "agent" .
<!-- End LinkedDoc RDF -->
*/
package logdrop

import (
	hclog "github.com/hashicorp/go-hclog"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

// Log provides a mock function with given fields: level, msg, args
func (_m *MockLogger) Log(level hclog.Level, msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, level, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewMockLogger creates a new instance of MockLogger. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockLogger(t testing.TB) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
