// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: BUSL-1.1

// Code generated by update-latest-versions.sh. DO NOT EDIT.

/*
# Module: testing/deployer/topology/default_versions.go
Default Versions module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<testing/deployer/topology/default_versions.go> a code:Module ;
    code:name "testing/deployer/topology/default_versions.go" ;
    code:description "Default Versions module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package topology

const (
	DefaultConsulCEImage         = "hashicorp/consul:1.21.4"
	DefaultConsulEnterpriseImage = "hashicorp/consul-enterprise:1.21.4-ent"
	DefaultEnvoyImage            = "envoyproxy/envoy:v1.35.6"
	DefaultDataplaneImage        = "hashicorp/consul-dataplane:1.8.1"
)
