// Code generated by mockery v2.15.0. DO NOT EDIT.

/*
# Module: agent/consul/auth/mock_ACLCache.go
Mock Aclcache module for agent layer

## Tags
access-control, agent, authentication, authorization, security

## Exports
MockACLCache, NewMockACLCache

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<agent/consul/auth/mock_ACLCache.go> a code:Module ;
    code:name "agent/consul/auth/mock_ACLCache.go" ;
    code:description "Mock Aclcache module for agent layer" ;
    code:language "go" ;
    code:layer "agent" ;
    code:exports :MockACLCache, :NewMockACLCache ;
    code:tags "access-control", "agent", "authentication", "authorization", "security" .
<!-- End LinkedDoc RDF -->
*/
package auth

import mock "github.com/stretchr/testify/mock"

// MockACLCache is an autogenerated mock type for the ACLCache type
type MockACLCache struct {
	mock.Mock
}

// RemoveIdentityWithSecretToken provides a mock function with given fields: secretToken
func (_m *MockACLCache) RemoveIdentityWithSecretToken(secretToken string) {
	_m.Called(secretToken)
}

type mockConstructorTestingTNewMockACLCache interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockACLCache creates a new instance of MockACLCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockACLCache(t mockConstructorTestingTNewMockACLCache) *MockACLCache {
	mock := &MockACLCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
