// Code generated by protoc-json-shim. DO NOT EDIT.

/*
# Module: proto-public/pbmulticluster/v2/computed_exported_services_json.gen.go
Computed Exported Services Json.Gen module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbmulticluster/v2/computed_exported_services_json.gen.go> a code:Module ;
    code:name "proto-public/pbmulticluster/v2/computed_exported_services_json.gen.go" ;
    code:description "Computed Exported Services Json.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package multiclusterv2

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for ComputedExportedServices
func (this *ComputedExportedServices) MarshalJSON() ([]byte, error) {
	str, err := ComputedExportedServicesMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ComputedExportedServices
func (this *ComputedExportedServices) UnmarshalJSON(b []byte) error {
	return ComputedExportedServicesUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for ComputedExportedService
func (this *ComputedExportedService) MarshalJSON() ([]byte, error) {
	str, err := ComputedExportedServicesMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ComputedExportedService
func (this *ComputedExportedService) UnmarshalJSON(b []byte) error {
	return ComputedExportedServicesUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for ComputedExportedServiceConsumer
func (this *ComputedExportedServiceConsumer) MarshalJSON() ([]byte, error) {
	str, err := ComputedExportedServicesMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ComputedExportedServiceConsumer
func (this *ComputedExportedServiceConsumer) UnmarshalJSON(b []byte) error {
	return ComputedExportedServicesUnmarshaler.Unmarshal(b, this)
}

var (
	ComputedExportedServicesMarshaler   = &protojson.MarshalOptions{}
	ComputedExportedServicesUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
