// Code generated by protoc-json-shim. DO NOT EDIT.

/*
# Module: proto-public/pbmulticluster/v2/exported_services_json.gen.go
Exported Services Json.Gen module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbmulticluster/v2/exported_services_json.gen.go> a code:Module ;
    code:name "proto-public/pbmulticluster/v2/exported_services_json.gen.go" ;
    code:description "Exported Services Json.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package multiclusterv2

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for ExportedServices
func (this *ExportedServices) MarshalJSON() ([]byte, error) {
	str, err := ExportedServicesMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ExportedServices
func (this *ExportedServices) UnmarshalJSON(b []byte) error {
	return ExportedServicesUnmarshaler.Unmarshal(b, this)
}

var (
	ExportedServicesMarshaler   = &protojson.MarshalOptions{}
	ExportedServicesUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
