// Code generated by protoc-json-shim. DO NOT EDIT.

/*
# Module: proto-public/pbmulticluster/v2/exported_services_consumer_json.gen.go
Exported Services Consumer Json.Gen module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbmulticluster/v2/exported_services_consumer_json.gen.go> a code:Module ;
    code:name "proto-public/pbmulticluster/v2/exported_services_consumer_json.gen.go" ;
    code:description "Exported Services Consumer Json.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package multiclusterv2

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for ExportedServicesConsumer
func (this *ExportedServicesConsumer) MarshalJSON() ([]byte, error) {
	str, err := ExportedServicesConsumerMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ExportedServicesConsumer
func (this *ExportedServicesConsumer) UnmarshalJSON(b []byte) error {
	return ExportedServicesConsumerUnmarshaler.Unmarshal(b, this)
}

var (
	ExportedServicesConsumerMarshaler   = &protojson.MarshalOptions{}
	ExportedServicesConsumerUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
