// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: pbmulticluster/v2/namespace_exported_services.proto

/*
# Module: proto-public/pbmulticluster/v2/namespace_exported_services.pb.binary.go
Namespace Exported Services.Pb.Binary module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbmulticluster/v2/namespace_exported_services.pb.binary.go> a code:Module ;
    code:name "proto-public/pbmulticluster/v2/namespace_exported_services.pb.binary.go" ;
    code:description "Namespace Exported Services.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package multiclusterv2

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *NamespaceExportedServices) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *NamespaceExportedServices) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
