// Code generated by protoc-json-shim. DO NOT EDIT.

/*
# Module: proto-public/pbmulticluster/v2/namespace_exported_services_json.gen.go
Namespace Exported Services Json.Gen module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbmulticluster/v2/namespace_exported_services_json.gen.go> a code:Module ;
    code:name "proto-public/pbmulticluster/v2/namespace_exported_services_json.gen.go" ;
    code:description "Namespace Exported Services Json.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package multiclusterv2

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for NamespaceExportedServices
func (this *NamespaceExportedServices) MarshalJSON() ([]byte, error) {
	str, err := NamespaceExportedServicesMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NamespaceExportedServices
func (this *NamespaceExportedServices) UnmarshalJSON(b []byte) error {
	return NamespaceExportedServicesUnmarshaler.Unmarshal(b, this)
}

var (
	NamespaceExportedServicesMarshaler   = &protojson.MarshalOptions{}
	NamespaceExportedServicesUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
