// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

/*
# Module: proto-public/pbmulticluster/v2/namespace_exported_services_deepcopy.gen.go
Namespace Exported Services Deepcopy.Gen module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbmulticluster/v2/namespace_exported_services_deepcopy.gen.go> a code:Module ;
    code:name "proto-public/pbmulticluster/v2/namespace_exported_services_deepcopy.gen.go" ;
    code:description "Namespace Exported Services Deepcopy.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package multiclusterv2

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using NamespaceExportedServices within kubernetes types, where deepcopy-gen is used.
func (in *NamespaceExportedServices) DeepCopyInto(out *NamespaceExportedServices) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceExportedServices. Required by controller-gen.
func (in *NamespaceExportedServices) DeepCopy() *NamespaceExportedServices {
	if in == nil {
		return nil
	}
	out := new(NamespaceExportedServices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceExportedServices. Required by controller-gen.
func (in *NamespaceExportedServices) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
