// Code generated by protoc-json-shim. DO NOT EDIT.

/*
# Module: proto-public/pbmulticluster/v2/partition_exported_services_json.gen.go
Partition Exported Services Json.Gen module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbmulticluster/v2/partition_exported_services_json.gen.go> a code:Module ;
    code:name "proto-public/pbmulticluster/v2/partition_exported_services_json.gen.go" ;
    code:description "Partition Exported Services Json.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package multiclusterv2

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for PartitionExportedServices
func (this *PartitionExportedServices) MarshalJSON() ([]byte, error) {
	str, err := PartitionExportedServicesMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PartitionExportedServices
func (this *PartitionExportedServices) UnmarshalJSON(b []byte) error {
	return PartitionExportedServicesUnmarshaler.Unmarshal(b, this)
}

var (
	PartitionExportedServicesMarshaler   = &protojson.MarshalOptions{}
	PartitionExportedServicesUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
