// Code generated by protoc-gen-resource-types. DO NOT EDIT.

/*
# Module: proto-public/pbmulticluster/v2/resources.rtypes.go
Resources.Rtypes module for internal layer

## Linked Modules
- [proto-public/pbresource](../proto-public/pbresource)

## Tags
data-model, internal, types

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbmulticluster/v2/resources.rtypes.go> a code:Module ;
    code:name "proto-public/pbmulticluster/v2/resources.rtypes.go" ;
    code:description "Resources.Rtypes module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:linksTo [
        code:name "proto-public/pbresource" ;
        code:path "../proto-public/pbresource"
    ] ;
    code:tags "data-model", "internal", "types" .
<!-- End LinkedDoc RDF -->
*/
package multiclusterv2

import (
	"github.com/hashicorp/consul/proto-public/pbresource"
)

const (
	GroupName = "multicluster"
	Version   = "v2"

	ComputedExportedServicesKind  = "ComputedExportedServices"
	ExportedServicesKind          = "ExportedServices"
	NamespaceExportedServicesKind = "NamespaceExportedServices"
	PartitionExportedServicesKind = "PartitionExportedServices"
)

var (
	ComputedExportedServicesType = &pbresource.Type{
		Group:        GroupName,
		GroupVersion: Version,
		Kind:         ComputedExportedServicesKind,
	}

	ExportedServicesType = &pbresource.Type{
		Group:        GroupName,
		GroupVersion: Version,
		Kind:         ExportedServicesKind,
	}

	NamespaceExportedServicesType = &pbresource.Type{
		Group:        GroupName,
		GroupVersion: Version,
		Kind:         NamespaceExportedServicesKind,
	}

	PartitionExportedServicesType = &pbresource.Type{
		Group:        GroupName,
		GroupVersion: Version,
		Kind:         PartitionExportedServicesKind,
	}
)
