// Code generated by protoc-gen-resource-types. DO NOT EDIT.

/*
# Module: proto/private/pbdemo/v2/resources.rtypes.go
Resources.Rtypes module for internal layer

## Linked Modules
- [proto-public/pbresource](../proto-public/pbresource)

## Tags
data-model, internal, types

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto/private/pbdemo/v2/resources.rtypes.go> a code:Module ;
    code:name "proto/private/pbdemo/v2/resources.rtypes.go" ;
    code:description "Resources.Rtypes module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:linksTo [
        code:name "proto-public/pbresource" ;
        code:path "../proto-public/pbresource"
    ] ;
    code:tags "data-model", "internal", "types" .
<!-- End LinkedDoc RDF -->
*/
package demov2

import (
	"github.com/hashicorp/consul/proto-public/pbresource"
)

const (
	GroupName = "demo"
	Version   = "v2"

	AlbumKind    = "Album"
	ArtistKind   = "Artist"
	FestivalKind = "Festival"
)

var (
	AlbumType = &pbresource.Type{
		Group:        GroupName,
		GroupVersion: Version,
		Kind:         AlbumKind,
	}

	ArtistType = &pbresource.Type{
		Group:        GroupName,
		GroupVersion: Version,
		Kind:         ArtistKind,
	}

	FestivalType = &pbresource.Type{
		Group:        GroupName,
		GroupVersion: Version,
		Kind:         FestivalKind,
	}
)
