// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

/*
# Module: grpcmocks/proto-public/pbacl/mock_UnsafeACLServiceServer.go
Mock Unsafeaclserviceserver module for internal layer

## Tags
access-control, api, authorization, communication, grpc, internal, networking, security

## Exports
NewUnsafeACLServiceServer, UnsafeACLServiceServer

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<grpcmocks/proto-public/pbacl/mock_UnsafeACLServiceServer.go> a code:Module ;
    code:name "grpcmocks/proto-public/pbacl/mock_UnsafeACLServiceServer.go" ;
    code:description "Mock Unsafeaclserviceserver module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:exports :NewUnsafeACLServiceServer, :UnsafeACLServiceServer ;
    code:tags "access-control", "api", "authorization", "communication", "grpc", "internal", "networking", "security" .
<!-- End LinkedDoc RDF -->
*/
package mockpbacl

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUnsafeACLServiceServer creates a new instance of UnsafeACLServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeACLServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeACLServiceServer {
	mock := &UnsafeACLServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnsafeACLServiceServer is an autogenerated mock type for the UnsafeACLServiceServer type
type UnsafeACLServiceServer struct {
	mock.Mock
}

type UnsafeACLServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeACLServiceServer) EXPECT() *UnsafeACLServiceServer_Expecter {
	return &UnsafeACLServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedACLServiceServer provides a mock function for the type UnsafeACLServiceServer
func (_mock *UnsafeACLServiceServer) mustEmbedUnimplementedACLServiceServer() {
	_mock.Called()
	return
}

// UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedACLServiceServer'
type UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedACLServiceServer is a helper method to define mock.On call
func (_e *UnsafeACLServiceServer_Expecter) mustEmbedUnimplementedACLServiceServer() *UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call {
	return &UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedACLServiceServer")}
}

func (_c *UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call) Run(run func()) *UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call) Return() *UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call) RunAndReturn(run func()) *UnsafeACLServiceServer_mustEmbedUnimplementedACLServiceServer_Call {
	_c.Run(run)
	return _c
}
