// Code generated by protoc-json-shim. DO NOT EDIT.

/*
# Module: proto-public/annotations/ratelimit/ratelimit_json.gen.go
Ratelimit Json.Gen module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/annotations/ratelimit/ratelimit_json.gen.go> a code:Module ;
    code:name "proto-public/annotations/ratelimit/ratelimit_json.gen.go" ;
    code:description "Ratelimit Json.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package ratelimit

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for Spec
func (this *Spec) MarshalJSON() ([]byte, error) {
	str, err := RatelimitMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Spec
func (this *Spec) UnmarshalJSON(b []byte) error {
	return RatelimitUnmarshaler.Unmarshal(b, this)
}

var (
	RatelimitMarshaler   = &protojson.MarshalOptions{}
	RatelimitUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
