// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: annotations/ratelimit/ratelimit.proto

/*
# Module: proto-public/annotations/ratelimit/ratelimit.pb.binary.go
Ratelimit.Pb.Binary module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/annotations/ratelimit/ratelimit.pb.binary.go> a code:Module ;
    code:name "proto-public/annotations/ratelimit/ratelimit.pb.binary.go" ;
    code:description "Ratelimit.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package ratelimit

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *Spec) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *Spec) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
