// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: pbserverdiscovery/serverdiscovery.proto

/*
# Module: proto-public/pbserverdiscovery/serverdiscovery.pb.binary.go
Serverdiscovery.Pb.Binary module for internal layer

## Tags
discovery, dns, internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbserverdiscovery/serverdiscovery.pb.binary.go> a code:Module ;
    code:name "proto-public/pbserverdiscovery/serverdiscovery.pb.binary.go" ;
    code:description "Serverdiscovery.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "discovery", "dns", "internal" .
<!-- End LinkedDoc RDF -->
*/
package pbserverdiscovery

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *WatchServersRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *WatchServersRequest) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *WatchServersResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *WatchServersResponse) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *Server) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *Server) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
