// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: private/pbconnect/connect.proto

/*
# Module: proto/private/pbconnect/connect.pb.binary.go
Connect.Pb.Binary module for internal layer

## Tags
internal, mtls, service-mesh

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto/private/pbconnect/connect.pb.binary.go> a code:Module ;
    code:name "proto/private/pbconnect/connect.pb.binary.go" ;
    code:description "Connect.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal", "mtls", "service-mesh" .
<!-- End LinkedDoc RDF -->
*/
package pbconnect

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *CARoots) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *CARoots) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *CARoot) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *CARoot) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *IssuedCert) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *IssuedCert) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
