// Code generated by mog. DO NOT EDIT.

/*
# Module: proto/private/pboperator/operator.gen.go
Operator.Gen module for internal layer

## Linked Modules
- [api](../api)

## Tags
internal

## Exports
TransferLeaderResponseFromAPI, TransferLeaderResponseToAPI

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto/private/pboperator/operator.gen.go> a code:Module ;
    code:name "proto/private/pboperator/operator.gen.go" ;
    code:description "Operator.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:linksTo [
        code:name "api" ;
        code:path "../api"
    ] ;
    code:exports :TransferLeaderResponseFromAPI, :TransferLeaderResponseToAPI ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package pboperator

import "github.com/hashicorp/consul/api"

func TransferLeaderResponseToAPI(s *TransferLeaderResponse, t *api.TransferLeaderResponse) {
	if s == nil {
		return
	}
	t.Success = s.Success
}
func TransferLeaderResponseFromAPI(t *api.TransferLeaderResponse, s *TransferLeaderResponse) {
	if s == nil {
		return
	}
	s.Success = t.Success
}
