// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: private/pboperator/operator.proto

/*
# Module: proto/private/pboperator/operator.pb.binary.go
Operator.Pb.Binary module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto/private/pboperator/operator.pb.binary.go> a code:Module ;
    code:name "proto/private/pboperator/operator.pb.binary.go" ;
    code:description "Operator.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package pboperator

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *TransferLeaderRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *TransferLeaderRequest) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *TransferLeaderResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *TransferLeaderResponse) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
