// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: pbdns/dns.proto

/*
# Module: proto-public/pbdns/dns.pb.binary.go
Dns.Pb.Binary module for internal layer

## Tags
discovery, internal, networking

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbdns/dns.pb.binary.go> a code:Module ;
    code:name "proto-public/pbdns/dns.pb.binary.go" ;
    code:description "Dns.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "discovery", "internal", "networking" .
<!-- End LinkedDoc RDF -->
*/
package pbdns

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *QueryRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *QueryRequest) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *QueryResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *QueryResponse) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
