// Code generated by protoc-gen-grpc-inmem. DO NOT EDIT.

/*
# Module: proto-public/pbdns/dns_cloning_grpc.pb.go
Dns Cloning Grpc.Pb module for internal layer

## Tags
api, communication, discovery, grpc, internal, networking

## Exports
CloningDNSServiceClient, IsCloningDNSServiceClient, NewCloningDNSServiceClient

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbdns/dns_cloning_grpc.pb.go> a code:Module ;
    code:name "proto-public/pbdns/dns_cloning_grpc.pb.go" ;
    code:description "Dns Cloning Grpc.Pb module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:exports :CloningDNSServiceClient, :IsCloningDNSServiceClient, :NewCloningDNSServiceClient ;
    code:tags "api", "communication", "discovery", "grpc", "internal", "networking" .
<!-- End LinkedDoc RDF -->
*/
package pbdns

import (
	"context"

	grpc "google.golang.org/grpc"
	"google.golang.org/protobuf/proto"
)

// compile-time check to ensure that the generator is implementing all
// of the grpc client interfaces methods.
var _ DNSServiceClient = CloningDNSServiceClient{}

// IsCloningDNSServiceClient is an interface that can be used to detect
// that a DNSServiceClient is using the in-memory transport and has already
// been wrapped with a with a CloningDNSServiceClient.
type IsCloningDNSServiceClient interface {
	IsCloningDNSServiceClient() bool
}

// CloningDNSServiceClient implements the DNSServiceClient interface by wrapping
// another implementation and copying all protobuf messages that pass through the client.
// This is mainly useful to wrap the an in-process client to insulate users of that
// client from having to care about potential immutability of data they receive or having
// the server implementation mutate their internal memory.
type CloningDNSServiceClient struct {
	DNSServiceClient
}

func NewCloningDNSServiceClient(client DNSServiceClient) DNSServiceClient {
	if cloner, ok := client.(IsCloningDNSServiceClient); ok && cloner.IsCloningDNSServiceClient() {
		// prevent a double clone if the underlying client is already the cloning client.
		return client
	}

	return CloningDNSServiceClient{
		DNSServiceClient: client,
	}
}

// IsCloningDNSServiceClient implements the IsCloningDNSServiceClient interface. This
// is only used to detect wrapped clients that would be double cloning data and prevent that.
func (c CloningDNSServiceClient) IsCloningDNSServiceClient() bool {
	return true
}

func (c CloningDNSServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	in = proto.Clone(in).(*QueryRequest)

	out, err := c.DNSServiceClient.Query(ctx, in)
	if err != nil {
		return nil, err
	}

	return proto.Clone(out).(*QueryResponse), nil
}
