// Code generated by protoc-json-shim. DO NOT EDIT.

/*
# Module: proto-public/pbdns/dns_json.gen.go
Dns Json.Gen module for internal layer

## Tags
discovery, internal, networking

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbdns/dns_json.gen.go> a code:Module ;
    code:name "proto-public/pbdns/dns_json.gen.go" ;
    code:description "Dns Json.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "discovery", "internal", "networking" .
<!-- End LinkedDoc RDF -->
*/
package pbdns

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for QueryRequest
func (this *QueryRequest) MarshalJSON() ([]byte, error) {
	str, err := DnsMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for QueryRequest
func (this *QueryRequest) UnmarshalJSON(b []byte) error {
	return DnsUnmarshaler.Unmarshal(b, this)
}

// MarshalJSON is a custom marshaler for QueryResponse
func (this *QueryResponse) MarshalJSON() ([]byte, error) {
	str, err := DnsMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for QueryResponse
func (this *QueryResponse) UnmarshalJSON(b []byte) error {
	return DnsUnmarshaler.Unmarshal(b, this)
}

var (
	DnsMarshaler   = &protojson.MarshalOptions{}
	DnsUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
