// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: BUSL-1.1

//go:build !consulent

/*
# Module: internal/resource/registry_ce.go
Registry Ce module for internal layer

## Linked Modules
- [proto-public/pbresource](../proto-public/pbresource)

## Tags
internal

## Exports
Registration

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<internal/resource/registry_ce.go> a code:Module ;
    code:name "internal/resource/registry_ce.go" ;
    code:description "Registry Ce module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:linksTo [
        code:name "proto-public/pbresource" ;
        code:path "../proto-public/pbresource"
    ] ;
    code:exports :Registration ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package resource

import (
	"google.golang.org/protobuf/proto"

	"github.com/hashicorp/consul/proto-public/pbresource"
)

type Registration struct {
	// Type is the GVK of the resource type.
	Type *pbresource.Type

	// Proto is the resource's protobuf message type.
	Proto proto.Message

	// ACLs are hooks called to perform authorization on RPCs.
	// The hooks can assume that Validate has been called.
	ACLs *ACLHooks

	// Validate is called to structurally validate the resource (e.g.
	// check for required fields). Validate can assume that Mutate
	// has been called.
	Validate ValidationHook

	// Mutate is called to fill out any autogenerated fields (e.g. UUIDs) or
	// apply defaults before validation. Mutate can assume that
	// Resource.ID is populated and has non-empty tenancy fields. This does
	// not mean those tenancy fields actually exist.
	Mutate MutationHook

	// Scope describes the tenancy scope of a resource.
	Scope Scope
}
