// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: pbdataplane/dataplane.proto

/*
# Module: proto-public/pbdataplane/dataplane.pb.binary.go
Dataplane.Pb.Binary module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbdataplane/dataplane.pb.binary.go> a code:Module ;
    code:name "proto-public/pbdataplane/dataplane.pb.binary.go" ;
    code:description "Dataplane.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package pbdataplane

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *GetSupportedDataplaneFeaturesRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *GetSupportedDataplaneFeaturesRequest) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *DataplaneFeatureSupport) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *DataplaneFeatureSupport) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *GetSupportedDataplaneFeaturesResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *GetSupportedDataplaneFeaturesResponse) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *GetEnvoyBootstrapParamsRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *GetEnvoyBootstrapParamsRequest) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *GetEnvoyBootstrapParamsResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *GetEnvoyBootstrapParamsResponse) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
