// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: private/pbautoconf/auto_config.proto

/*
# Module: proto/private/pbautoconf/auto_config.pb.binary.go
Auto Config.Pb.Binary module for internal layer

## Tags
configuration, internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto/private/pbautoconf/auto_config.pb.binary.go> a code:Module ;
    code:name "proto/private/pbautoconf/auto_config.pb.binary.go" ;
    code:description "Auto Config.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "configuration", "internal" .
<!-- End LinkedDoc RDF -->
*/
package pbautoconf

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *AutoConfigRequest) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *AutoConfigRequest) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *AutoConfigResponse) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *AutoConfigResponse) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
