// Code generated by protoc-json-shim. DO NOT EDIT.

/*
# Module: proto-public/pbresource/annotations_json.gen.go
Annotations Json.Gen module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbresource/annotations_json.gen.go> a code:Module ;
    code:name "proto-public/pbresource/annotations_json.gen.go" ;
    code:description "Annotations Json.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package pbresource

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON is a custom marshaler for ResourceTypeSpec
func (this *ResourceTypeSpec) MarshalJSON() ([]byte, error) {
	str, err := AnnotationsMarshaler.Marshal(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ResourceTypeSpec
func (this *ResourceTypeSpec) UnmarshalJSON(b []byte) error {
	return AnnotationsUnmarshaler.Unmarshal(b, this)
}

var (
	AnnotationsMarshaler   = &protojson.MarshalOptions{}
	AnnotationsUnmarshaler = &protojson.UnmarshalOptions{DiscardUnknown: false}
)
