// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

/*
# Module: proto-public/pbresource/annotations_deepcopy.gen.go
Annotations Deepcopy.Gen module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbresource/annotations_deepcopy.gen.go> a code:Module ;
    code:name "proto-public/pbresource/annotations_deepcopy.gen.go" ;
    code:description "Annotations Deepcopy.Gen module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package pbresource

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ResourceTypeSpec within kubernetes types, where deepcopy-gen is used.
func (in *ResourceTypeSpec) DeepCopyInto(out *ResourceTypeSpec) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTypeSpec. Required by controller-gen.
func (in *ResourceTypeSpec) DeepCopy() *ResourceTypeSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTypeSpec. Required by controller-gen.
func (in *ResourceTypeSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
