// Code generated by protoc-gen-grpc-inmem. DO NOT EDIT.

/*
# Module: proto-public/pbresource/cloning_stream.pb.go
Cloning Stream.Pb module for internal layer

## Tags
internal

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto-public/pbresource/cloning_stream.pb.go> a code:Module ;
    code:name "proto-public/pbresource/cloning_stream.pb.go" ;
    code:description "Cloning Stream.Pb module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "internal" .
<!-- End LinkedDoc RDF -->
*/
package pbresource

import (
	grpc "google.golang.org/grpc"
	"google.golang.org/protobuf/proto"
)

type serverStream[T proto.Message] interface {
	Recv() (T, error)
	grpc.ClientStream
}

type cloningStream[T proto.Message] struct {
	serverStream[T]
}

func newCloningStream[T proto.Message](stream serverStream[T]) cloningStream[T] {
	return cloningStream[T]{serverStream: stream}
}

func (st cloningStream[T]) Recv() (T, error) {
	var zero T
	val, err := st.serverStream.Recv()
	if err != nil {
		return zero, err
	}

	return proto.Clone(val).(T), nil
}
