// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: simple.proto

/*
# Module: agent/grpc-middleware/testutil/testservice/simple.pb.binary.go
Simple.Pb.Binary module for agent layer

## Tags
agent, api, communication, grpc, networking

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<agent/grpc-middleware/testutil/testservice/simple.pb.binary.go> a code:Module ;
    code:name "agent/grpc-middleware/testutil/testservice/simple.pb.binary.go" ;
    code:description "Simple.Pb.Binary module for agent layer" ;
    code:language "go" ;
    code:layer "agent" ;
    code:tags "agent", "api", "communication", "grpc", "networking" .
<!-- End LinkedDoc RDF -->
*/
package testservice

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *Req) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *Req) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *Resp) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *Resp) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
