// Code generated by mockery v2.15.0. DO NOT EDIT.

/*
# Module: agent/cache/mock_Request.go
Mock Request module for agent layer

## Tags
agent

## Exports
MockRequest, NewMockRequest

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<agent/cache/mock_Request.go> a code:Module ;
    code:name "agent/cache/mock_Request.go" ;
    code:description "Mock Request module for agent layer" ;
    code:language "go" ;
    code:layer "agent" ;
    code:exports :MockRequest, :NewMockRequest ;
    code:tags "agent" .
<!-- End LinkedDoc RDF -->
*/
package cache

import mock "github.com/stretchr/testify/mock"

// MockRequest is an autogenerated mock type for the Request type
type MockRequest struct {
	mock.Mock
}

// CacheInfo provides a mock function with given fields:
func (_m *MockRequest) CacheInfo() RequestInfo {
	ret := _m.Called()

	var r0 RequestInfo
	if rf, ok := ret.Get(0).(func() RequestInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(RequestInfo)
	}

	return r0
}

type mockConstructorTestingTNewMockRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRequest creates a new instance of MockRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRequest(t mockConstructorTestingTNewMockRequest) *MockRequest {
	mock := &MockRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
