// Code generated by mockery v2.15.0. DO NOT EDIT.

/*
# Module: agent/grpc-external/services/acl/mock_TokenWriter.go
Mock Tokenwriter module for agent layer

## Tags
access-control, agent, api, authorization, communication, grpc, networking, security

## Exports
MockTokenWriter, NewMockTokenWriter

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<agent/grpc-external/services/acl/mock_TokenWriter.go> a code:Module ;
    code:name "agent/grpc-external/services/acl/mock_TokenWriter.go" ;
    code:description "Mock Tokenwriter module for agent layer" ;
    code:language "go" ;
    code:layer "agent" ;
    code:exports :MockTokenWriter, :NewMockTokenWriter ;
    code:tags "access-control", "agent", "api", "authorization", "communication", "grpc", "networking", "security" .
<!-- End LinkedDoc RDF -->
*/
package acl

import mock "github.com/stretchr/testify/mock"

// MockTokenWriter is an autogenerated mock type for the TokenWriter type
type MockTokenWriter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: secretID, fromLogout
func (_m *MockTokenWriter) Delete(secretID string, fromLogout bool) error {
	ret := _m.Called(secretID, fromLogout)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(secretID, fromLogout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockTokenWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTokenWriter creates a new instance of MockTokenWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTokenWriter(t mockConstructorTestingTNewMockTokenWriter) *MockTokenWriter {
	mock := &MockTokenWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
