// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: private/pbacl/acl.proto

/*
# Module: proto/private/pbacl/acl.pb.binary.go
Acl.Pb.Binary module for internal layer

## Tags
access-control, authorization, internal, security

<!-- LinkedDoc RDF -->
@prefix code: <https://schema.codedoc.org/> .
<proto/private/pbacl/acl.pb.binary.go> a code:Module ;
    code:name "proto/private/pbacl/acl.pb.binary.go" ;
    code:description "Acl.Pb.Binary module for internal layer" ;
    code:language "go" ;
    code:layer "internal" ;
    code:tags "access-control", "authorization", "internal", "security" .
<!-- End LinkedDoc RDF -->
*/
package pbacl

import (
	"google.golang.org/protobuf/proto"
)

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *ACLLink) MarshalBinary() ([]byte, error) {
	return proto.Marshal(msg)
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *ACLLink) UnmarshalBinary(b []byte) error {
	return proto.Unmarshal(b, msg)
}
